name: fluent-bit
#image: quay.io/samsung_cnct/fluent-bit-container:0.0.7-38f1e50123c23ca3bfece1a3b61a8cc4884be6a9
image: fluent/fluent-bit:0.14
cluster_uuid: 00000000-0000-0000-0000-000000000000
resources:
  requests:
    cpu: 100m
    mem: 500Mi
  limits:
    cpu: 300m
    mem: 1000Mi
elasticSearchHost: elasticsearch
elasticSearchPort: 9200
elasticSearchUsername: elastic
elasticSearchPassword: changeme
fluentTimeStamp: flutime 
