---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.name}}
  labels:
    component: {{.Values.name}}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: "{{template "namewithversion" .}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
